export class AudioSystem{
  constructor(settings){this.settings=settings;this.ctx=null;this.master=null;this.music=null;this.sfx=null;this.started=false;this.intensity=0;}
  unlock(){ if(this.ctx){if(this.ctx.state==='suspended')this.ctx.resume();return;} this.ctx=new (window.AudioContext||window.webkitAudioContext)(); this.master=this.ctx.createGain();this.music=this.ctx.createGain();this.sfx=this.ctx.createGain(); this.music.connect(this.master);this.sfx.connect(this.master);this.master.connect(this.ctx.destination);this.apply(); this.startDrone(); }
  apply(){ if(!this.ctx)return; this.master.gain.value=this.settings.master;this.music.gain.value=this.settings.music*0.22;this.sfx.gain.value=this.settings.sfx*0.5; }
  tone(freq=220,dur=.08,type='square',gain=.08,detune=0){if(!this.ctx)return;const o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.value=freq;o.detune.value=detune;g.gain.setValueAtTime(gain,this.ctx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,this.ctx.currentTime+dur);o.connect(g);g.connect(this.sfx);o.start();o.stop(this.ctx.currentTime+dur);}
  noise(dur=.09,gain=.06,high=700){if(!this.ctx)return;const n=Math.ceil(this.ctx.sampleRate*dur),buf=this.ctx.createBuffer(1,n,this.ctx.sampleRate),d=buf.getChannelData(0);for(let i=0;i<n;i++)d[i]=(Math.random()*2-1)*(1-i/n);const s=this.ctx.createBufferSource(),f=this.ctx.createBiquadFilter(),g=this.ctx.createGain();s.buffer=buf;f.type='lowpass';f.frequency.value=high;g.gain.value=gain;s.connect(f);f.connect(g);g.connect(this.sfx);s.start();}
  play(name){switch(name){case'shot':this.noise(.07,.18,1900);this.tone(90,.08,'square',.07);break;case'shotgun':this.noise(.14,.28,1100);this.tone(60,.12,'sawtooth',.09);break;case'suppressed':this.noise(.04,.08,800);this.tone(120,.04,'triangle',.03);break;case'melee':this.noise(.045,.1,650);this.tone(75,.05,'square',.05);break;case'kill':this.tone(54,.12,'sawtooth',.08);break;case'door':this.noise(.1,.12,500);this.tone(110,.07,'square',.03);break;case'glass':this.noise(.18,.13,4800);break;case'reload':this.tone(520,.025,'square',.03);setTimeout(()=>this.tone(360,.025,'square',.025),90);break;case'empty':this.tone(900,.025,'square',.025);break;case'pickup':this.tone(620,.05,'triangle',.04);this.tone(930,.06,'triangle',.025);break;case'hurt':this.noise(.08,.15,500);break;case'dash':this.noise(.06,.08,1800);break;case'step':this.noise(.025,.018,380);break;case'heartbeat':this.tone(54,.08,'sine',.055);setTimeout(()=>this.tone(48,.06,'sine',.035),110);break;case'ui':this.tone(440,.035,'square',.02);break;case'boss':this.tone(45,.4,'sawtooth',.08);break;}}
  musicTone(freq=110,dur=.08,type='triangle',gain=.025){if(!this.ctx)return;const o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(gain,this.ctx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,this.ctx.currentTime+dur);o.connect(g);g.connect(this.music);o.start();o.stop(this.ctx.currentTime+dur);}
  startDrone(){if(this.started||!this.ctx)return;this.started=true;const o=this.ctx.createOscillator(),o2=this.ctx.createOscillator(),g=this.ctx.createGain();o.type='sawtooth';o.frequency.value=43.65;o2.type='triangle';o2.frequency.value=65.4;g.gain.value=.065;o.connect(g);o2.connect(g);g.connect(this.music);o.start();o2.start();this.droneGain=g;this.beat=0;this.beatTimer=setInterval(()=>{if(!this.ctx||this.ctx.state!=='running')return;this.beat++;if(this.beat%4===0)this.musicTone(55,.12,'square',.026+.02*this.intensity);if(this.intensity>.35&&this.beat%2===0)this.musicTone(110,.045,'triangle',.012*this.intensity);if(this.intensity>.7)this.musicTone(1500,.018,'square',.005);},250);}
  setIntensity(v){this.intensity=v;if(this.droneGain)this.droneGain.gain.setTargetAtTime(.05+v*.08,this.ctx.currentTime,.15)}
}
