import { VIRTUAL_W,VIRTUAL_H,UPGRADES,MASKS,COLORS } from '../data/config.js';
import { Input } from './Input.js';
import { AudioSystem } from './Audio.js';
import { loadSave,storeSave } from './Save.js';
import { Level } from '../world/Level.js';
import { Player } from '../entities/Player.js';
import { Enemy } from '../entities/Enemy.js';
import { Boss } from '../entities/Boss.js';
import { FX } from '../systems/FX.js';
import { makeWeapon } from '../combat/weapons.js';
import { clamp,dist,angleDiff,pointSegDist,choose,rand } from './math.js';
import * as THREE from 'three';
import { moodColor } from '../render/mood.js';
export class Game{
 constructor(canvas,renderer){this.canvas=canvas;this.renderer=renderer||null;this.ctx=canvas.getContext('2d',{alpha:false});this.ctx.imageSmoothingEnabled=false;this.input=new Input(renderer&&renderer.available?renderer.canvas:canvas);this.save=loadSave();this.settings=this.save.settings;this.audio=new AudioSystem(this.settings);this.fx=new FX();this.fx.bloodEnabled=this.settings.blood;this.fx.quality=this.settings.quality;this.fx.quality=this.settings.quality;this.applyDomSettings();this.state='menu';this.menuIndex=0;this.settingsIndex=0;this.cam={x:0,y:0,tx:0,ty:0};this.shakeMag=0;this.shakeX=0;this.shakeY=0;this.debug=false;this.invincible=false;this.last=performance.now();this.acc=0;this.aiStep=.1;this.fps=60;this.fpsT=0;this.frames=0;this.uiCanvas=document.getElementById('ui');this.uiCtx=this.uiCanvas?this.uiCanvas.getContext('2d'):this.ctx;if(this.uiCtx)this.uiCtx.imageSmoothingEnabled=false;this.applyRenderSettings();this.resize();addEventListener('resize',()=>this.resize());}
 applyRenderSettings(){if(!this.renderer||!this.renderer.available)return;this.renderer.setPost(!!this.settings.post);this.renderer.setQuality(this.settings.quality);}
 resize(){const ratio=VIRTUAL_W/VIRTUAL_H,w=innerWidth,h=innerHeight;let cw=w,ch=w/ratio;if(ch>h){ch=h;cw=h*ratio}const size={width:`${Math.floor(cw)}px`,height:`${Math.floor(ch)}px`};for(const id of ['game','gl','ui']){const el=document.getElementById(id);if(el)Object.assign(el.style,size);}}
 start(){requestAnimationFrame(t=>this.loop(t));}
 loop(t){const raw=Math.min(.05,(t-this.last)/1000);this.last=t;this.update(raw);this.render();this.input.endFrame();this.frames++;this.fpsT+=raw;if(this.fpsT>.5){this.fps=Math.round(this.frames/this.fpsT);this.frames=0;this.fpsT=0}requestAnimationFrame(x=>this.loop(x));}
 unlockAudio(){this.audio.unlock();this.audio.apply()}
 applyDomSettings(){const s=document.getElementById('scanlines');if(s)s.style.display=this.settings.post?'block':'none';}
 startRun(){this.unlockAudio();this.state='playing';this.level=new Level();this.player=new Player(180,520);this.applyMask();this.enemies=[];this.boss=null;this.projectiles=[];this.thrown=[];this.hazards=[];this.fx=new FX();this.fx.bloodEnabled=this.settings.blood;this.fx.quality=this.settings.quality;this.phase=0;this.upgradeShown=false;this.upgradeChoices=[];this.objectiveReady=false;this.score=0;this.combo=0;this.comboT=0;this.maxCombo=0;this.runTime=0;this.deaths=0;this.shots=0;this.hits=0;this.stealthKills=0;this.weaponKinds=new Set();this.killCount=0;this.heartT=0;this.deathT=0;this.roomClearT=0;this.worldCanvas=null;this.worldCtx=null;this.decalDrawn=0;this.corpseDrawn=0;this.cam.x=0;this.cam.y=250;this.spawnPhase0();this.audio.setIntensity(.1);this.applyRenderSettings();}
 applyMask(){const id=this.save.selectedMask||'MOTH-0';this.player.maskId=id;if(id==='MOTH-0')this.player.comboBonus+=.35;if(id==='RAM-7')this.player.breachBonus=1;if(id==='FOX-2'){this.player.noiseMul*=.68;this.player.detectionMul=.82}if(id==='RAVEN-3')this.player.thrownBonus=1;}
 cycleMask(dir=1){const unlocked=MASKS.filter(m=>this.save.unlockedMasks.includes(m.id));let i=Math.max(0,unlocked.findIndex(m=>m.id===this.save.selectedMask));i=(i+dir+unlocked.length)%unlocked.length;this.save.selectedMask=unlocked[i].id;storeSave(this.save);this.audio.play('ui');}
 spawnPhase0(){const E=(x,y,t,w)=>this.enemies.push(new Enemy(x+rand(-10,10),y+rand(-10,10),t,w));E(510,250,choose(['guard','guard','brawler']),[{x:450,y:250},{x:590,y:250}]);E(770,320,'brawler',[{x:730,y:190},{x:810,y:350}]);E(1010,290,choose(['guard','hunter']),[{x:950,y:220},{x:1090,y:330}]);E(1320,300,'shotgunner',[{x:1280,y:210},{x:1450,y:320}]);E(730,690,choose(['guard','brawler']),[{x:720,y:610},{x:870,y:820}]);E(1075,730,choose(['hunter','guard']),[{x:1010,y:590},{x:1130,y:830}]);E(1390,800,'elite',[{x:1280,y:780},{x:1480,y:840}]);}
 spawnPhase1(){this.enemies=[];const E=(x,y,t)=>this.enemies.push(new Enemy(x+rand(-12,12),y+rand(-12,12),t,[]));E(620,470,choose(['guard','brawler']));E(920,470,choose(['hunter','elite']));E(1190,470,'shotgunner');E(1090,830,choose(['brawler','guard']));this.boss=new Boss(1400,805);this.audio.setIntensity(.8);}
 update(dt){
   if((this.input.pressed.size||this.input.mouse.leftPressed||this.input.mouse.rightPressed)&&!this.audio.ctx)this.unlockAudio();
   if(this.input.tap('F1'))this.debug=!this.debug;if(this.input.tap('F2'))this.invincible=!this.invincible;
   if(this.state==='menu'){this.updateMenu();return}if(this.state==='settings'){this.updateSettings();return}if(this.state==='credits'){if(this.input.tap('Escape')||this.input.tap('Enter'))this.state='menu';return}if(this.state==='results'){if(this.input.tap('Enter'))this.state='menu';if(this.input.tap('KeyR'))this.startRun();return}
   if(this.state==='upgrade'){this.updateUpgrade();return}if(this.state==='paused'){if(this.input.tap('Escape'))this.state='playing';return}
   if(this.state!=='playing')return;if((this.freeze||0)>0){this.freeze-=dt;this.fx.update(dt);return}if(this.input.tap('Escape')){this.state='paused';return}if(this.input.tap('F3'))this.enemies.push(new Enemy(this.player.x+80,this.player.y,'guard',[]));if(this.input.tap('F4')){for(const e of this.enemies)e.dead=true;if(this.boss)this.boss.dead=true}
       this.runTime+=dt;this.heartT-=dt;this.audio.decayPulse(dt);if(this.player.hp===1&&this.heartT<=0){this.heartT=.9;this.audio.play('heartbeat')}this.comboT-=dt;if(this.comboT<=0)this.combo=0;if(this.player.dead){this.deathT+=dt;if(this.deathT>.72)this.restartAfterDeath();return}
   this.player.update(dt,this);this.updateCamera(dt);this.fx.update(dt);this.updateProjectiles(dt);this.updateThrown(dt);this.updateHazards(dt);
   this.acc+=dt;if(this.acc>=this.aiStep){for(const e of this.enemies)e.perceive(this);this.acc=0}
   for(const e of this.enemies)e.update(dt,this);if(this.boss)this.boss.update(dt,this);this.enemies=this.enemies.filter(e=>!e._remove);
   const alive=this.enemies.some(e=>!e.dead);if(this.phase===0&&!alive&&!this.upgradeShown){this.roomClearT+=dt;if(this.roomClearT>.65){this.showUpgrade();}}
   if(this.phase===1&&!alive&&(!this.boss||this.boss.dead)&&!this.objectiveReady){this.objectiveReady=true;this.level.objective={x:1400,y:810,taken:false};this.audio.setIntensity(.15);this.score+=1500;}
   this.audio.setIntensity(clamp((this.enemies.filter(e=>e.state==='COMBAT'&&!e.dead).length+(this.boss&&!this.boss.dead?3:0))/7,0.08,1));
   this.shakeMag*=Math.pow(.025,dt);this.shakeX=rand(-this.shakeMag,this.shakeMag);this.shakeY=rand(-this.shakeMag,this.shakeMag);
 }
 updateMenu(){const items=5;if(this.input.tap('ArrowDown')||this.input.tap('KeyS')){this.menuIndex=(this.menuIndex+1)%items;this.audio.play('ui')}if(this.input.tap('ArrowUp')||this.input.tap('KeyW')){this.menuIndex=(this.menuIndex+items-1)%items;this.audio.play('ui')}if(this.menuIndex===1&&(this.input.tap('ArrowLeft')||this.input.tap('KeyA')))this.cycleMask(-1);if(this.menuIndex===1&&(this.input.tap('ArrowRight')||this.input.tap('KeyD')))this.cycleMask(1);if(this.input.tap('Enter')||this.input.mouse.leftPressed){if(this.input.mouse.leftPressed){const y=this.input.mouse.y;this.menuIndex=clamp(Math.floor((y-270)/40),0,4)}if(this.menuIndex===0)this.startRun();if(this.menuIndex===1)this.cycleMask(1);if(this.menuIndex===2)this.state='settings';if(this.menuIndex===3)this.state='credits';if(this.menuIndex===4)location.reload();}}
 updateSettings(){const keys=['master','music','sfx','shake','blood','quality','post','flashes','highContrastCursor'];if(this.input.tap('Escape')){this.save.settings=this.settings;storeSave(this.save);this.state='menu';return}if(this.input.tap('ArrowDown')||this.input.tap('KeyS'))this.settingsIndex=(this.settingsIndex+1)%keys.length;if(this.input.tap('ArrowUp')||this.input.tap('KeyW'))this.settingsIndex=(this.settingsIndex+keys.length-1)%keys.length;const k=keys[this.settingsIndex],dir=(this.input.tap('ArrowRight')||this.input.tap('KeyD')?1:0)-(this.input.tap('ArrowLeft')||this.input.tap('KeyA')?1:0);if(dir){if(typeof this.settings[k]==='boolean')this.settings[k]=!this.settings[k];else this.settings[k]=clamp(this.settings[k]+dir*.1,0,1);this.audio.apply();this.fx.bloodEnabled=this.settings.blood;this.fx.quality=this.settings.quality;this.applyDomSettings();this.applyRenderSettings();this.audio.play('ui')}}
 showUpgrade(){this.upgradeShown=true;this.state='upgrade';const pool=[...UPGRADES];this.upgradeChoices=[];while(this.upgradeChoices.length<3){const u=pool.splice((Math.random()*pool.length)|0,1)[0];this.upgradeChoices.push(u)}this.audio.play('ui')}
 updateUpgrade(){let idx=-1;if(this.input.tap('Digit1'))idx=0;if(this.input.tap('Digit2'))idx=1;if(this.input.tap('Digit3'))idx=2;if(this.input.mouse.leftPressed){const x=this.input.mouse.x;idx=clamp(Math.floor((x-135)/235),0,2)}if(idx>=0){this.upgradeChoices[idx].apply(this.player);this.phase=1;this.spawnPhase1();this.state='playing';this.audio.play('pickup')}}
 restartAfterDeath(){const deaths=this.deaths;this.startRun();this.deaths=deaths;}
 screenToWorld(x,y){return{x:x+this.cam.x-this.shakeX,y:y+this.cam.y-this.shakeY}}
 updateCamera(dt){const mouseWorld=this.screenToWorld(this.input.mouse.x,this.input.mouse.y),dx=clamp(mouseWorld.x-this.player.x,-240,240),dy=clamp(mouseWorld.y-this.player.y,-140,140);this.cam.tx=clamp(this.player.x-VIRTUAL_W/2+dx*.18,0,this.level.w-VIRTUAL_W);this.cam.ty=clamp(this.player.y-VIRTUAL_H/2+dy*.18,0,this.level.h-VIRTUAL_H);this.cam.x+=(this.cam.tx-this.cam.x)*(1-Math.pow(.001,dt));this.cam.y+=(this.cam.ty-this.cam.y)*(1-Math.pow(.001,dt));}
 shake(n){this.shakeMag=Math.max(this.shakeMag,n*this.settings.shake)}
 emitNoise(x,y,radius,type='noise'){const ev={x,y,radius,type};for(const e of this.enemies)e.hearNoise(ev,this);if(this.debug)this.fx.flash(x,y,radius,'#4ad9d3',.08)}
 alertNearby(x,y,r,target){for(const e of this.enemies){if(!e.dead&&dist(e,{x,y})<r&&e.state!=='COMBAT'){e.state='INVESTIGATE';e.lastKnown={x:target.x,y:target.y};e.searchT=3}}}
 fireWeapon(shooter,w,a){const enemy=shooter!==this.player;const count=w.pellets||1;if(!enemy){this.shots+=count;this.weaponKinds.add(w.id)}for(let n=0;n<count;n++){const aa=a+rand(-(w.spread||0)*this.playerSpread(enemy),(w.spread||0)*this.playerSpread(enemy));const speed=w.id==='shotgun'?780:980;this.projectiles.push({x:shooter.x+Math.cos(aa)*22,y:shooter.y+Math.sin(aa)*22,px:shooter.x,py:shooter.y,vx:Math.cos(aa)*speed,vy:Math.sin(aa)*speed,damage:w.damage,owner:enemy?'enemy':'player',life:(w.range||800)/speed,color:enemy?'#ee8d55':'#f4cf7a',ricochet:!enemy&&this.player.ricochet?1:0});}
   const sx=shooter.x+Math.cos(a)*25,sy=shooter.y+Math.sin(a)*25;this.fx.flash(sx,sy,w.id==='shotgun'?75:45,'#ffd28c',.06);this.fx.burst(sx,sy,w.id==='shotgun'?10:4,'#e5b86e',100,.2,2);this.emitNoise(shooter.x,shooter.y,w.noise, 'gunshot');this.shake(enemy?1.5:(w.id==='shotgun'?6:w.id==='revolver'?4:2));this.audio.play(w.id==='shotgun'?'shotgun':w.id==='suppressed'?'suppressed':'shot');}
 playerSpread(enemy){return enemy?1:(this.player?.spreadMul||1)}
 enemyShoot(e,w,a){this.fireWeapon(e,w,a);}
 enemyMelee(e,p){this.fx.burst(p.x,p.y,5,'#d0c9ac',90,.25,3);if(!this.invincible)p.damage(1,this,e.a);this.shake(4);this.audio.play('melee');}
 meleeAttack(attacker,w,a){this.weaponKinds.add(w.id);let hit=false;for(const e of this.enemies){if(e.dead)continue;const d=dist(attacker,e),da=Math.abs(angleDiff(a,Math.atan2(e.y-attacker.y,e.x-attacker.x)));if(d<w.range+e.r&&da<w.arc*.5){e.damage(w.damage*this.player.meleeMul,this,a,w.knock);hit=true;}}
   if(this.boss&&!this.boss.dead&&dist(attacker,this.boss)<w.range+this.boss.r)this.boss.damage(w.damage*this.player.meleeMul,this,a);for(const p of this.level.props){if(!p.broken&&dist(attacker,{x:p.x+p.w/2,y:p.y+p.h/2})<w.range+20){if(this.level.damageProp(p,1)){this.fx.burst(p.x+p.w/2,p.y+p.h/2,12,p.type==='glass'?'#7fdad8':'#8b7663',170,.45,3);if(p.type==='glass'){this.audio.play('glass');this.emitNoise(p.x,p.y,260,'glass')}if(p.type==='barrel')this.explodeAt(p.x+p.w/2,p.y+p.h/2)}}}
   this.fx.burst(attacker.x+Math.cos(a)*34,attacker.y+Math.sin(a)*34,hit?12:5,hit?'#d4b169':'#88858c',120,.28,3);this.shake(hit?5:2);this.audio.play('melee');if(hit)this.hitStop(.028);}
 throwWeapon(attacker,w,a){this.weaponKinds.add(w.id);this.thrown.push({x:attacker.x,y:attacker.y,vx:Math.cos(a)*560,vy:Math.sin(a)*560,a,spin:8,weapon:{...w},life:1.3});this.emitNoise(attacker.x,attacker.y,65,'throw');}
 updateThrown(dt){for(const t of this.thrown){const ox=t.x,oy=t.y;t.x+=t.vx*dt;t.y+=t.vy*dt;t.a+=t.spin*dt;t.life-=dt;t.vx*=Math.pow(.45,dt);t.vy*=Math.pow(.45,dt);const wall=this.level.bulletHit(ox,oy,t.x,t.y);if(wall){t.life=0;this.fx.burst(t.x,t.y,7,'#aaa',100,.3,2)}for(const e of this.enemies){if(!e.dead&&dist(t,e)<e.r+8){if(t.weapon.kind==='melee')e.damage((t.weapon.damage>=2?2:1)+this.player.thrownBonus,this,Math.atan2(t.vy,t.vx),200);else if(this.player.thrownBonus)e.damage(this.player.thrownBonus,this,Math.atan2(t.vy,t.vx),180);else e.stunHit(this,Math.atan2(t.vy,t.vx),190);t.life=0;break}}if(t.life<=0&&!t.dropped){t.dropped=true;this.level.pickups.push({x:t.x,y:t.y,weapon:makeWeapon(t.weapon.id)})}}
   this.thrown=this.thrown.filter(t=>t.life>0);}
 spawnHazard(x,y,a){this.hazards.push({x,y,vx:Math.cos(a)*360,vy:Math.sin(a)*360,r:10,life:1.5});this.emitNoise(x,y,220,'debris');}
 updateHazards(dt){for(const h of this.hazards){h.x+=h.vx*dt;h.y+=h.vy*dt;h.a=(h.a||0)+dt*7;h.life-=dt;if(this.level.blocked(h.x,h.y,h.r)){h.life=0;this.fx.burst(h.x,h.y,9,'#8c6c52',130,.35,3)}if(dist(h,this.player)<h.r+this.player.r){if(!this.invincible)this.player.damage(1,this,Math.atan2(h.vy,h.vx));h.life=0}}this.hazards=this.hazards.filter(h=>h.life>0)}
 explodeAt(x,y){this.renderer?.glitch?.(1);this.fx.flash(x,y,120,'#f2a54f',.12);this.fx.burst(x,y,28,'#d27d43',260,.65,5);this.emitNoise(x,y,780,'explosion');this.shake(11);this.audio.play('shotgun');for(const e of this.enemies){if(!e.dead&&dist(e,{x,y})<92)e.damage(3,this,Math.atan2(e.y-y,e.x-x),320)}if(this.boss&&!this.boss.dead&&dist(this.boss,{x,y})<100)this.boss.damage(3,this,0);if(!this.player.dead&&dist(this.player,{x,y})<84&&!this.invincible)this.player.damage(2,this,Math.atan2(this.player.y-y,this.player.x-x));}
 updateProjectiles(dt){for(const b of this.projectiles){const ox=b.x,oy=b.y;b.px=ox;b.py=oy;b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;const wall=this.level.bulletHit(ox,oy,b.x,b.y);if(wall){if('hp'in wall&&this.level.damageProp(wall,b.damage)){this.fx.burst(b.x,b.y,10,wall.type==='glass'?'#71d4d2':'#9b745a',150,.35,3);if(wall.type==='glass'){this.audio.play('glass');this.emitNoise(b.x,b.y,260,'glass')}if(wall.type==='barrel')this.explodeAt(wall.x+wall.w/2,wall.y+wall.h/2)}if(b.ricochet>0){b.ricochet--;if(Math.abs(b.vx)>Math.abs(b.vy))b.vx*=-1;else b.vy*=-1;b.x=ox;b.y=oy;this.fx.burst(ox,oy,6,'#f0c66d',100,.2,2)}else b.life=0;}
      if(b.life<=0)continue;if(b.owner==='player'){for(const e of this.enemies){if(!e.dead&&pointSegDist(e.x,e.y,ox,oy,b.x,b.y)<e.r){e.damage(b.damage,this,Math.atan2(b.vy,b.vx),90);this.hits++;b.life=0;break}}if(b.life>0&&this.boss&&!this.boss.dead&&pointSegDist(this.boss.x,this.boss.y,ox,oy,b.x,b.y)<this.boss.r){this.boss.damage(b.damage,this,Math.atan2(b.vy,b.vx));this.hits++;b.life=0}}
      else if(!this.player.dead&&pointSegDist(this.player.x,this.player.y,ox,oy,b.x,b.y)<this.player.r){if(!this.invincible)this.player.damage(b.damage,this,Math.atan2(b.vy,b.vx));b.life=0}}
    this.projectiles=this.projectiles.filter(b=>b.life>0);}
 interact(kick){if(this.player.dead)return;for(const e of this.enemies){if(!e.dead&&e.stun>0&&dist(this.player,e)<38&&kick){e.damage(99,this,this.player.a,260);this.score+=250;if(this.player.execRestoresDash)this.player.dashCd=0;this.hitStop(.055);return}}
   if(this.level.objective&&!this.level.objective.taken&&dist(this.player,this.level.objective)<48){this.level.objective.taken=true;this.finishRun();return}
   if(!kick){let best=null,bd=48;for(const p of this.level.pickups){if(p.taken)continue;const d=dist(this.player,p);if(d<bd){best=p;bd=d}}if(best){best.taken=true;this.player.equip(best.weapon,this);return}}
   const d=this.level.nearestDoor(this.player,58);if(d){this.level.openDoor(d,kick);this.audio.play('door');this.emitNoise(d.x,d.y,kick?340:80,kick?'breach':'door');if(kick){this.shake(5);for(const e of this.enemies){const c={x:d.x+d.w/2,y:d.y+d.h/2};if(!e.dead&&dist(e,c)<62)e.damage(2+this.player.breachBonus,this,this.player.a,280+this.player.breachBonus*70)}}}}
 onEnemyKilled(e,angle){this.killCount++;const wasStealth=e.state!=='COMBAT';if(wasStealth)this.stealthKills++;this.fx.blood(e.x,e.y,14,angle);this.fx.burst(e.x,e.y,10,'#ff7a1a',120,.3,2);this.fx.corpses.push({x:e.x,y:e.y,a:angle});while(this.fx.corpses.length>40)this.fx.corpses.shift();this.fx.pool(e.x,e.y,1.5);this.audio.play('kill');this.shake(4);this.hitStop(.032);this.addCombo(wasStealth?175:120);if(Math.random()<.48&&e.weapon)this.level.pickups.push({x:e.x,y:e.y,weapon:makeWeapon(e.weapon.id)});}
 onBossKilled(b){this.fx.blood(b.x,b.y,28,this.player.a);this.fx.burst(b.x,b.y,24,'#d4b46a',230,.7,5);this.score+=1800;this.addCombo(500);this.shake(12);this.hitStop(.07);}
 addCombo(base){this.combo++;this.comboT=2.25+this.player.comboBonus;this.maxCombo=Math.max(this.maxCombo,this.combo);this.score+=Math.round(base*(1+Math.min(3,this.combo*.18)));}
 hitStop(sec){this.freeze=Math.max(this.freeze||0,sec)}
 onPlayerDeath(){this.deaths++;this.audio.setIntensity(.05);this.shake(13);this.hitStop(.05);this.renderer?.glitch?.(1)}
 finishRun(){const acc=this.shots?this.hits/this.shots:1;let value=this.score+Math.max(0,3200-this.runTime*20)+this.maxCombo*90+acc*700-this.deaths*450;let rank='D';if(value>3000)rank='C';if(value>4800)rank='B';if(value>6500)rank='A';if(value>8200)rank='S';if(value>10000)rank='S+';const unlocks=[];this.results={score:Math.round(this.score),time:this.runTime,accuracy:Math.round(acc*100),combo:this.maxCombo,deaths:this.deaths,variety:this.weaponKinds.size,stealth:this.stealthKills,rank,value:Math.round(value),unlocks};this.save.runs++;if(!this.save.unlockedMasks.includes('RAM-7')){this.save.unlockedMasks.push('RAM-7');unlocks.push('RAM-7')}if(['A','S','S+'].includes(rank)&&!this.save.unlockedMasks.includes('FOX-2')){this.save.unlockedMasks.push('FOX-2');unlocks.push('FOX-2')}if(this.maxCombo>=6&&!this.save.unlockedMasks.includes('RAVEN-3')){this.save.unlockedMasks.push('RAVEN-3');unlocks.push('RAVEN-3')}if(value>this.save.highScore){this.save.highScore=Math.round(value);this.save.bestRank=rank}storeSave(this.save);this.state='results';this.audio.setIntensity(.08)}
 render(){if(this.renderer&&this.renderer.available)return this.renderGL();return this.renderCanvas();}
 renderCanvas(){const c=this.ctx;c.setTransform(1,0,0,1,0,0);c.fillStyle='#05060a';c.fillRect(0,0,VIRTUAL_W,VIRTUAL_H);if(this.state==='menu'){this.drawMenu(c);return}if(this.state==='settings'){this.drawSettings(c);return}if(this.state==='credits'){this.drawCredits(c);return}if(this.state==='results'){this.drawResults(c);return}if(!this.level){return}
   c.save();c.translate(-this.cam.x+this.shakeX,-this.cam.y+this.shakeY);this.level.draw(c);this.fx.drawDecals(c);for(const b of this.projectiles){c.strokeStyle=b.color;c.lineWidth=2;c.beginPath();c.moveTo(b.px,b.py);c.lineTo(b.x,b.y);c.stroke()}for(const t of this.thrown){c.save();c.translate(t.x,t.y);c.rotate(t.a);c.fillStyle=t.weapon.color;c.fillRect(-10,-3,20,6);c.restore()}for(const h of this.hazards){c.save();c.translate(h.x,h.y);c.rotate(h.a||0);c.fillStyle='#8f6c4e';c.fillRect(-9,-7,18,14);c.restore()}for(const e of this.enemies)e.draw(c,this.debug);if(this.boss)this.boss.draw(c);this.fx.draw(c);this.player.draw(c);c.restore();
    this.drawLighting(c);this.drawHUD(c);if(this.state==='upgrade')this.drawUpgrade(c);if(this.state==='paused')this.drawPause(c);if(this.player.dead)this.drawDeath(c);this.drawPost(c);if(this.debug)this.drawDebug(c);
  }
  ensureWorld(){if(!this.worldCanvas){this.worldCanvas=document.createElement('canvas');this.worldCanvas.width=this.level.w;this.worldCanvas.height=this.level.h;this.worldCtx=this.worldCanvas.getContext('2d');this.worldCtx.imageSmoothingEnabled=false;this.level.markDirty();}if(this.level.dirty){this.rebakeWorld();this.level.dirty=false;}this.drainDecalsAndCorpses();}
  rebakeWorld(){this.level.bake(this.worldCtx);for(const d of this.fx.decals)this.level.paintDecal(this.worldCtx,d);for(const c of this.fx.corpses)this.level.paintCorpse(this.worldCtx,c);this.decalDrawn=this.fx.decals.length;this.corpseDrawn=this.fx.corpses.length;}
  drainDecalsAndCorpses(){for(let i=this.decalDrawn||0;i<this.fx.decals.length;i++)this.level.paintDecal(this.worldCtx,this.fx.decals[i]);this.decalDrawn=this.fx.decals.length;for(let i=this.corpseDrawn||0;i<this.fx.corpses.length;i++)this.level.paintCorpse(this.worldCtx,this.fx.corpses[i]);this.corpseDrawn=this.fx.corpses.length;}
  beatPulse(){return this.settings.music>0?(this.audio.pulse||0)*Math.min(1,(this.audio.intensity||0)+.35):0}
  pushLights(){if(!this.renderer||!this.renderer.available||!this.level)return;const pulse=this.beatPulse(),lights=[];for(const l of this.level.lights){const mood=l.mood||this.level.zoneAt(l.x,l.y);lights.push({sx:l.x-this.cam.x+this.shakeX,sy:l.y-this.cam.y+this.shakeY,radius:l.r,intensity:.62,color:new THREE.Color(moodColor(mood,'glow',pulse))})}for(const f of this.fx.flashes){lights.push({sx:f.x-this.cam.x+this.shakeX,sy:f.y-this.cam.y+this.shakeY,radius:f.r*2.2,intensity:1.2,color:new THREE.Color(f.color)})}this.renderer.setLights({lights,ambient:.5,pulse,flashPos:null,flashArc:.6})}
  renderGL(){const ui=this.uiCtx||this.ctx;if(ui){ui.setTransform(1,0,0,1,0,0);ui.clearRect(0,0,VIRTUAL_W,VIRTUAL_H);}const c=this.renderer.albedoCtx,g=this.renderer.emissiveCtx;c.setTransform(1,0,0,1,0,0);c.fillStyle=COLORS.void;c.fillRect(0,0,VIRTUAL_W,VIRTUAL_H);    g.setTransform(1,0,0,1,0,0);g.fillStyle='#000000';g.fillRect(0,0,VIRTUAL_W,VIRTUAL_H);
    if(this.state==='menu'||this.state==='settings'||this.state==='credits'||this.state==='results')this.renderer.setLights({lights:[],ambient:1,pulse:this.beatPulse()});
    if(this.state==='menu'){this.drawMenuWorld(c);this.renderer.render();this.drawMenuUI();return}if(this.state==='settings'){this.drawMenuWorld(c);this.renderer.render();this.drawSettings(ui);return}if(this.state==='credits'){this.drawMenuWorld(c);this.renderer.render();this.drawCredits(ui);return}if(this.state==='results'){this.drawResultsWorld(c);this.renderer.render();this.drawResults(ui);return}if(!this.level){this.renderer.render();return}
    this.ensureWorld();const ox=-this.cam.x+this.shakeX,oy=-this.cam.y+this.shakeY;c.drawImage(this.worldCanvas,this.cam.x-this.shakeX,this.cam.y-this.shakeY,VIRTUAL_W,VIRTUAL_H,0,0,VIRTUAL_W,VIRTUAL_H);c.save();c.translate(ox,oy);
    for(const b of this.projectiles){c.strokeStyle=b.color;c.lineWidth=2;c.beginPath();c.moveTo(b.px,b.py);c.lineTo(b.x,b.y);c.stroke()}
    for(const t of this.thrown){c.save();c.translate(t.x,t.y);c.rotate(t.a);c.fillStyle=t.weapon.color;c.fillRect(-10,-3,20,6);c.restore()}
    for(const h of this.hazards){c.save();c.translate(h.x,h.y);c.rotate(h.a||0);c.fillStyle='#8f6c4e';c.fillRect(-9,-7,18,14);c.restore()}
    for(const e of this.enemies)e.draw(c,this.debug);if(this.boss)this.boss.draw(c);this.fx.draw(c);if(!this.player.dead)this.player.draw(c);c.restore();
    g.save();g.globalCompositeOperation='lighter';g.translate(ox,oy);
    for(const b of this.projectiles){g.strokeStyle=b.color;g.lineWidth=3;g.globalAlpha=.45;g.beginPath();g.moveTo(b.px,b.py);g.lineTo(b.x,b.y);g.stroke()}g.globalAlpha=1;
    this.fx.drawGlow(g);for(const e of this.enemies)e.drawGlow(g);if(this.boss)this.boss.drawGlow(g);if(!this.player.dead)this.player.drawGlow(g);g.restore();
    this.pushLights();this.renderer.render();this.drawHUD(ui);if(this.state==='upgrade')this.drawUpgrade(ui);if(this.state==='paused')this.drawPause(ui);if(this.player.dead)this.drawDeath(ui);if(this.debug)this.drawDebug(ui);
  }
  drawMenuWorld(c){const t=performance.now()/1000,pulse=this.beatPulse();c.fillStyle=COLORS.void;c.fillRect(0,0,VIRTUAL_W,VIRTUAL_H);const g=c.createLinearGradient(0,300,0,540);g.addColorStop(0,'rgba(139,43,255,0)');g.addColorStop(1,`rgba(255,30,156,${.16+.12*pulse})`);c.fillStyle=g;c.fillRect(0,300,VIRTUAL_W,240);c.save();c.strokeStyle=COLORS.cyan;c.globalAlpha=.16;c.lineWidth=2;for(let i=0;i<70;i++){const x=(i*137+t*220)%960,y=(i*97+t*640)%540;c.beginPath();c.moveTo(x,y);c.lineTo(x-8,y+20);c.stroke()}c.restore();c.save();c.globalAlpha=.55+.35*Math.abs(Math.sin(t*2.3));c.fillStyle=COLORS.hotPink;c.shadowColor=COLORS.hotPink;c.shadowBlur=22;c.font='bold 20px monospace';c.fillText('MOTEL',64,300);c.restore();}
  drawResultsWorld(c){const t=performance.now()/1000;c.fillStyle=COLORS.void;c.fillRect(0,0,VIRTUAL_W,VIRTUAL_H);c.save();c.strokeStyle=COLORS.hotPink;c.globalAlpha=.12;c.lineWidth=2;for(let i=0;i<50;i++){const x=(i*191+t*160)%960,y=(i*83+t*420)%540;c.beginPath();c.moveTo(x,y);c.lineTo(x-7,y+18);c.stroke()}c.restore();}
  drawMenuUI(){const c=this.uiCtx;if(!c)return;this.drawMenu(c);}
 drawLighting(c){c.save();c.fillStyle='rgba(3,4,8,.33)';c.fillRect(0,0,VIRTUAL_W,VIRTUAL_H);c.globalCompositeOperation='lighter';const glow=(x,y,r,a=.15,color='220,190,135')=>{x=x-this.cam.x+this.shakeX;y=y-this.cam.y+this.shakeY;const g=c.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,`rgba(${color},${a})`);g.addColorStop(1,`rgba(${color},0)`);c.fillStyle=g;c.beginPath();c.arc(x,y,r,0,Math.PI*2);c.fill()};for(let i=0;i<this.level.lights.length;i++){if(this.settings.quality<.45&&i%2)continue;const l=this.level.lights[i];glow(l.x,l.y,l.r,.11)}glow(this.player.x,this.player.y,105,.08,'90,205,200');for(const f of this.fx.flashes)glow(f.x,f.y,f.r*1.8,this.settings.flashes?.24:.08,'255,197,112');c.restore();}
 drawHUD(c){if(!c||!this.player)return;const pulse=this.beatPulse(),p=this.player;c.save();c.font='bold 14px monospace';c.textBaseline='top';
   c.fillStyle='rgba(11,4,22,.72)';c.fillRect(16,16,236,66);c.strokeStyle=COLORS.hotPink;c.lineWidth=1.5;c.strokeRect(16.5,16.5,235,65);
   c.fillStyle=COLORS.cyan;c.fillText(`VEIL // ${p.maskId}`,28,25);
   for(let i=0;i<p.maxHp;i++){c.fillStyle=i<p.hp?COLORS.hotPink:'#2a1030';c.fillRect(28+i*17,50,12,8);c.strokeStyle=COLORS.ink;c.strokeRect(28.5+i*17,50.5,11,7)}
   const w=p.current;c.fillStyle=COLORS.bone;c.font='bold 12px monospace';c.fillText(`${w.name.toUpperCase()} ${w.kind==='gun'?`${w.ammo}/${w.reserve}`:'MELEE'}`,112,50);
   c.textAlign='right';c.fillStyle=COLORS.orange;c.font='bold 16px monospace';c.fillText(`SCORE ${String(this.score).padStart(6,'0')}`,VIRTUAL_W-22,22);
   if(this.combo>1){const s=1+pulse*.18;c.save();c.translate(VIRTUAL_W-30,64);c.scale(s,s);c.textAlign='right';c.font='bold 22px monospace';c.fillStyle=COLORS.hotPink;c.fillText(`CHAIN x${this.combo}`,0,0);c.restore();c.fillStyle=COLORS.ink;c.fillRect(VIRTUAL_W-145,78,120,4);c.fillStyle=COLORS.cyan;c.fillRect(VIRTUAL_W-145,78,120*clamp(this.comboT/(2.25+p.comboBonus),0,1),4)}
   c.textAlign='left';c.fillStyle=COLORS.ink;c.fillRect(28,70,86,5);c.fillStyle=COLORS.cyan;c.fillRect(28,70,86*(1-clamp(p.dashCd/p.dashCooldown,0,1)),5);
   const prompt=this.contextPrompt();if(prompt){c.textAlign='center';c.fillStyle='rgba(11,4,22,.82)';c.fillRect(340,487,280,28);c.strokeStyle=COLORS.cyan;c.lineWidth=1.5;c.strokeRect(340.5,487.5,279,27);c.fillStyle=COLORS.bone;c.font='bold 13px monospace';c.fillText(prompt,480,495)}
   if(this.runTime<3.2){c.textAlign='center';c.font='11px monospace';c.fillStyle=COLORS.orange;c.fillText('UNKNOWN CALL // ROOM 12. TAKE THE TAPE. DON’T PLAY IT.',480,58)}
   const tut=this.tutorialText();if(tut){c.textAlign='center';c.font='bold 14px monospace';c.fillStyle='rgba(11,4,22,.68)';c.fillRect(340,92,280,25);c.fillStyle=COLORS.cyan;c.fillText(tut,480,98)}
   c.restore();this.drawReticle(c)}
 contextPrompt(){if(this.level.objective&&!this.level.objective.taken&&dist(this.player,this.level.objective)<55)return '[E] TAKE THE STATIC TAPE';for(const e of this.enemies)if(!e.dead&&e.stun>0&&dist(this.player,e)<42)return '[SPACE] FINISH';for(const p of this.level.pickups)if(!p.taken&&dist(this.player,p)<48)return `[E] TAKE ${p.weapon.name.toUpperCase()}`;const d=this.level.nearestDoor(this.player,58);if(d&&!d.open)return '[E] OPEN  /  [SPACE] BREACH';return ''}
 tutorialText(){if(this.phase!==0)return'';if(this.runTime<3.8)return'WASD  MOVE';if(this.runTime<7.5)return'MOUSE  AIM';if(this.runTime<11)return'CLICK  ATTACK';if(this.runTime<14.5)return'E  PICK UP / OPEN';if(this.runTime<18)return'SHIFT  DASH';return''}
 drawReticle(c){const m=this.input.mouse;c.save();c.translate(m.x,m.y);c.strokeStyle=this.settings.highContrastCursor?'#ffffff':COLORS.cyan;c.lineWidth=1.5;const r=8+(this.player?.attackCd||0)*7;c.beginPath();c.moveTo(-r-5,0);c.lineTo(-r,0);c.moveTo(r,0);c.lineTo(r+5,0);c.moveTo(0,-r-5);c.lineTo(0,-r);c.moveTo(0,r);c.lineTo(0,r+5);c.stroke();c.restore()}
 drawPost(c){if(!this.settings.post)return;c.save();const g=c.createRadialGradient(480,270,180,480,270,570);g.addColorStop(0,'rgba(0,0,0,0)');g.addColorStop(1,'rgba(0,0,0,.55)');c.fillStyle=g;c.fillRect(0,0,960,540);c.globalAlpha=.035;c.fillStyle='#fff';for(let i=0;i<55;i++)c.fillRect((i*137+performance.now()*.02)%960,(i*83)%540,1,1);c.restore()}
 drawMenu(c){if(!(this.renderer&&this.renderer.available)){c.fillStyle=COLORS.void;c.fillRect(0,0,960,540)}c.save();c.translate(275,178);c.rotate(-.08);c.shadowColor=COLORS.hotPink;c.shadowBlur=20;c.fillStyle=COLORS.bone;c.beginPath();c.moveTo(-60,-78);c.lineTo(20,-88);c.lineTo(74,-40);c.lineTo(65,38);c.lineTo(3,78);c.lineTo(-70,39);c.lineTo(-85,-28);c.closePath();c.fill();c.shadowBlur=0;c.fillStyle=COLORS.ink;c.fillRect(-20,-38,32,10);c.fillRect(23,0,34,8);c.fillRect(-52,8,28,7);c.fillStyle=COLORS.hotPink;c.fillRect(50,-34,11,47);c.restore();c.textAlign='left';c.fillStyle=COLORS.bone;c.font='bold 46px monospace';c.fillText('VEIL//DRIVE',385,150);c.font='13px monospace';c.fillStyle=COLORS.cyan;c.fillText('MOTEL STATIC — A NEON CRIME ROGUELITE',389,175);const items=['START RUN',`MASK / ${this.save.selectedMask}`,'SETTINGS','CREDITS','RELOAD PAGE'];for(let i=0;i<items.length;i++){const y=270+i*40;c.fillStyle=i===this.menuIndex?COLORS.hotPink:'#6f5f7a';c.font=i===this.menuIndex?'bold 18px monospace':'16px monospace';c.fillText(`${i===this.menuIndex?'› ':''}${items[i]}`,390,y)}c.font='10px monospace';c.fillStyle='#786f79';c.fillText('← → CHANGE UNLOCKED MASK WHEN SELECTED',390,474);c.font='11px monospace';c.fillStyle=COLORS.orange;c.fillText(`BEST ${this.save.bestRank}  ${String(this.save.highScore).padStart(6,'0')}  //  RUNS ${this.save.runs}`,390,493);c.fillStyle='#8f7f9a';c.fillText('ENTER / CLICK SELECT   •   ↑↓ NAVIGATE',390,512);}
 drawSettings(c){c.fillStyle='rgba(11,4,22,.86)';c.fillRect(0,0,960,540);c.fillStyle=COLORS.bone;c.font='bold 30px monospace';c.fillText('SETTINGS / ACCESSIBILITY',90,70);const entries=[['MASTER','master'],['MUSIC','music'],['SFX','sfx'],['SCREEN SHAKE','shake'],['BLOOD FX','blood'],['GRAPHICS QUALITY','quality'],['POST PROCESS','post'],['FLASHING','flashes'],['HIGH-CONTRAST CURSOR','highContrastCursor']];for(let i=0;i<entries.length;i++){const[name,k]=entries[i],y=120+i*36;c.fillStyle=i===this.settingsIndex?COLORS.hotPink:'#8f7f9a';c.font=i===this.settingsIndex?'bold 15px monospace':'14px monospace';c.fillText(name,130,y);const v=this.settings[k];c.textAlign='right';c.fillStyle=i===this.settingsIndex?COLORS.cyan:COLORS.bone;c.fillText(typeof v==='boolean'?(v?'ON':'OFF'):`${Math.round(v*100)}%`,780,y);c.textAlign='left'}c.fillStyle='#8f7f9a';c.font='11px monospace';c.fillText('↑↓ SELECT   ←→ ADJUST   ESC SAVE/BACK',130,488);}
 drawCredits(c){c.fillStyle='rgba(11,4,22,.86)';c.fillRect(0,0,960,540);c.textAlign='center';c.fillStyle=COLORS.bone;c.font='bold 30px monospace';c.fillText('VEIL//DRIVE',480,90);c.font='13px monospace';c.fillStyle=COLORS.cyan;c.fillText('Original browser prototype',480,130);c.fillStyle='#9e8fa8';c.fillText('Code, procedural art, synthesis and systems generated for this project.',480,174);c.fillText('No third-party art, music, sound, or game assets are included.',480,198);c.fillStyle=COLORS.hotPink;c.fillText('Protagonist: MOTH-0  •  Boss: THE PORTER',480,242);c.fillStyle='#8f7f9a';c.fillText('ESC / ENTER BACK',480,450);c.textAlign='left'}
 drawUpgrade(c){c.fillStyle='rgba(11,4,22,.82)';c.fillRect(0,0,960,540);c.textAlign='center';c.fillStyle=COLORS.bone;c.font='bold 24px monospace';c.fillText('CHOOSE A BAD HABIT',480,115);for(let i=0;i<3;i++){const x=135+i*235,u=this.upgradeChoices[i];c.fillStyle='rgba(26,10,51,.92)';c.fillRect(x,165,205,190);c.strokeStyle=i===1?COLORS.hotPink:COLORS.violet;c.lineWidth=2;c.strokeRect(x+1,166,203,188);c.fillStyle=COLORS.hotPink;c.font='bold 13px monospace';c.fillText(`[${i+1}]`,x+102,190);c.fillStyle=COLORS.bone;c.font='bold 15px monospace';c.fillText(u.name,x+102,225);c.fillStyle=COLORS.cyan;c.font='12px monospace';this.wrapText(c,u.desc,x+102,260,170,18)}c.fillStyle='#8f7f9a';c.font='11px monospace';c.fillText('1 / 2 / 3 OR CLICK',480,395);c.textAlign='left'}
 wrapText(c,text,x,y,max,line){const words=text.split(' ');let row='';for(const w of words){const test=row+w+' ';if(c.measureText(test).width>max){c.fillText(row,x,y);y+=line;row=w+' '}else row=test}c.fillText(row,x,y)}
 drawPause(c){c.fillStyle='rgba(11,4,22,.8)';c.fillRect(0,0,960,540);c.textAlign='center';c.fillStyle=COLORS.bone;c.font='bold 28px monospace';c.fillText('PAUSED',480,225);c.fillStyle=COLORS.cyan;c.font='12px monospace';c.fillText('ESC RESUME',480,268);c.textAlign='left'}
 drawDeath(c){c.fillStyle='rgba(255,10,60,.12)';c.fillRect(0,0,960,540);c.textAlign='center';c.fillStyle=COLORS.blood;c.font='bold 30px monospace';c.fillText('SIGNAL LOST',480,250);c.font='12px monospace';c.fillStyle=COLORS.hotPink;c.fillText('REWINDING…',480,285);c.textAlign='left'}
 drawResults(c){if(!c)return;const r=this.results;c.fillStyle='rgba(11,4,22,.86)';c.fillRect(0,0,960,540);c.fillStyle=COLORS.bone;c.font='bold 26px monospace';c.fillText('MOTEL STATIC // CLOSED FILE',100,72);c.fillStyle=COLORS.hotPink;c.font='bold 86px monospace';c.fillText(r.rank,720,92);c.font='13px monospace';const rows=[['RUN VALUE',r.value],['COMBAT SCORE',r.score],['CLEAR TIME',`${r.time.toFixed(1)}s`],['ACCURACY',`${r.accuracy}%`],['MAX CHAIN',`x${r.combo}`],['DEATHS',r.deaths],['WEAPON VARIETY',r.variety],['SILENT KILLS',r.stealth]];for(let i=0;i<rows.length;i++){const y=150+i*34;c.fillStyle='#8f7f9a';c.fillText(rows[i][0],130,y);c.fillStyle=COLORS.bone;c.fillText(String(rows[i][1]),430,y)}if(r.unlocks?.length){c.fillStyle=COLORS.cyan;c.fillText(`UNLOCKED MASK: ${r.unlocks.join(' / ')}`,130,440)}c.fillStyle='#8f7f9a';c.fillText('ENTER MENU   •   R RUN AGAIN',130,472)}
 drawDebug(c){c.fillStyle='rgba(0,0,0,.7)';c.fillRect(8,90,170,90);c.fillStyle='#7be0d8';c.font='10px monospace';c.fillText(`FPS ${this.fps}`,16,101);c.fillText(`XY ${this.player.x|0},${this.player.y|0}`,16,116);c.fillText(`AI ${this.enemies.filter(e=>!e.dead).length}`,16,131);c.fillText(`STATE ${this.state}`,16,146);c.fillText(`F2 GOD ${this.invincible?'ON':'OFF'}  F3 SPAWN F4 CLEAR`,16,161);c.save();c.translate(-this.cam.x,-this.cam.y);for(const e of this.enemies){if(e.dead)continue;c.strokeStyle='rgba(80,220,210,.22)';c.beginPath();c.moveTo(e.x,e.y);c.arc(e.x,e.y,e.vision,e.a-e.fov/2,e.a+e.fov/2);c.closePath();c.stroke()}c.restore()}
}
