// HUD, markers, menus and end-of-run screens. This is the presentation layer
// for every game state; it only reads game state (plus `results`/`upgradeChoices`).
import { VIRTUAL_W, VIRTUAL_H, COLORS } from '../data/config.js';
import { clamp, dist } from '../core/math.js';
import { drawWeaponArt } from '../render/weapons-art.js';
import { MISSIONS, MISSION_COUNT } from '../data/missions.js';

export const HudSystem = {
  drawMenuWorld(c) { const t = performance.now() / 1000, pulse = this.beatPulse(); c.fillStyle = COLORS.void; c.fillRect(0, 0, VIRTUAL_W, VIRTUAL_H); const g = c.createLinearGradient(0, 300, 0, 540); g.addColorStop(0, 'rgba(139,43,255,0)'); g.addColorStop(1, `rgba(255,30,156,${.16 + .12 * pulse})`); c.fillStyle = g; c.fillRect(0, 300, VIRTUAL_W, 240); c.save(); c.strokeStyle = COLORS.cyan; c.globalAlpha = .16; c.lineWidth = 2; for (let i = 0; i < 70; i++) { const x = (i * 137 + t * 220) % 960, y = (i * 97 + t * 640) % 540; c.beginPath(); c.moveTo(x, y); c.lineTo(x - 8, y + 20); c.stroke(); } c.restore(); c.save(); c.globalAlpha = .55 + .35 * Math.abs(Math.sin(t * 2.3)); c.fillStyle = COLORS.hotPink; c.shadowColor = COLORS.hotPink; c.shadowBlur = 22; c.font = 'bold 20px monospace'; c.fillText('MOTEL', 64, 300); c.restore(); },
  drawResultsWorld(c) { const t = performance.now() / 1000; c.fillStyle = COLORS.void; c.fillRect(0, 0, VIRTUAL_W, VIRTUAL_H); c.save(); c.strokeStyle = COLORS.hotPink; c.globalAlpha = .12; c.lineWidth = 2; for (let i = 0; i < 50; i++) { const x = (i * 191 + t * 160) % 960, y = (i * 83 + t * 420) % 540; c.beginPath(); c.moveTo(x, y); c.lineTo(x - 7, y + 18); c.stroke(); } c.restore(); },
  drawMenuUI() { const c = this.uiCtx; if (!c) return; this.drawMenu(c); },
  drawLighting(c) { c.save(); c.fillStyle = 'rgba(3,4,8,.33)'; c.fillRect(0, 0, VIRTUAL_W, VIRTUAL_H); c.globalCompositeOperation = 'lighter'; const glow = (x, y, r, a = .15, color = '220,190,135') => { x = x - this.cam.x + this.shakeX; y = y - this.cam.y + this.shakeY; const g = c.createRadialGradient(x, y, 0, x, y, r); g.addColorStop(0, `rgba(${color},${a})`); g.addColorStop(1, `rgba(${color},0)`); c.fillStyle = g; c.beginPath(); c.arc(x, y, r, 0, Math.PI * 2); c.fill(); }; for (let i = 0; i < this.level.lights.length; i++) { if (this.settings.quality < .45 && i % 2) continue; const l = this.level.lights[i]; glow(l.x, l.y, l.r, .11); } glow(this.player.x, this.player.y, 105, .08, '90,205,200'); for (const f of this.fx.flashes) glow(f.x, f.y, f.r * 1.8, this.settings.flashes ? .24 : .08, '255,197,112'); c.restore(); },
  drawHUD(c) {
    if (!c || !this.player) return;
    const pulse = this.beatPulse(), p = this.player; c.save(); c.font = 'bold 14px monospace'; c.textBaseline = 'top';
    c.fillStyle = 'rgba(11,4,22,.72)'; c.fillRect(16, 16, 236, 66); c.strokeStyle = COLORS.hotPink; c.lineWidth = 1.5; c.strokeRect(16.5, 16.5, 235, 65);
    c.fillStyle = COLORS.cyan; c.fillText(`VEIL // ${p.maskId}`, 28, 25);
    for (let i = 0; i < p.maxHp; i++) { const hx = 33 + i * 13, hy = 54, hs = 5.5; c.beginPath(); c.moveTo(hx, hy + hs); c.bezierCurveTo(hx - hs * 1.35, hy + hs * .1, hx - hs * .95, hy - hs * 1.05, hx - hs * .36, hy - hs * .55); c.bezierCurveTo(hx - hs * .14, hy - hs * .38, hx - hs * .03, hy - hs * .24, hx, hy - hs * .1); c.bezierCurveTo(hx + hs * .03, hy - hs * .24, hx + hs * .14, hy - hs * .38, hx + hs * .36, hy - hs * .55); c.bezierCurveTo(hx + hs * .95, hy - hs * 1.05, hx + hs * 1.35, hy + hs * .1, hx, hy + hs); c.closePath(); c.fillStyle = i < p.hp ? COLORS.hotPink : '#2a1030'; c.fill(); c.strokeStyle = COLORS.ink; c.lineWidth = 1.3; c.stroke(); }
    const w = p.current; c.save(); c.translate(104, 56); drawWeaponArt(c, w, 0.8, '#e0a97f'); c.restore(); c.fillStyle = COLORS.bone; c.font = 'bold 12px monospace'; c.fillText(`${w.name.toUpperCase()} ${w.kind === 'gun' ? `${w.ammo}/${p.magOf(w)}·${w.reserve}` : 'MELEE'}`, 126, 50); if (p.reloadT > 0 && p.reloadWeapon) { const tot = p.reloadWeapon.reload * p.reloadMul; c.fillStyle = COLORS.ink; c.fillRect(126, 64, 110, 4); c.fillStyle = COLORS.orange; c.fillRect(126, 64, 110 * clamp(1 - p.reloadT / tot, 0, 1), 4); }
    c.textAlign = 'right'; c.fillStyle = COLORS.orange; c.font = 'bold 16px monospace'; c.fillText(`SCORE ${String(this.score).padStart(6, '0')}`, VIRTUAL_W - 22, 22);
    if (this.combo > 1) { const s = 1 + pulse * .18; c.save(); c.translate(VIRTUAL_W - 30, 64); c.scale(s, s); c.textAlign = 'right'; c.font = 'bold 22px monospace'; c.fillStyle = COLORS.hotPink; c.fillText(`CHAIN x${this.combo}`, 0, 0); c.restore(); c.fillStyle = COLORS.ink; c.fillRect(VIRTUAL_W - 145, 78, 120, 4); c.fillStyle = COLORS.cyan; c.fillRect(VIRTUAL_W - 145, 78, 120 * clamp(this.comboT / (2.25 + p.comboBonus), 0, 1), 4); }
    c.textAlign = 'left'; c.fillStyle = COLORS.ink; c.fillRect(28, 70, 86, 5); c.fillStyle = COLORS.cyan; c.fillRect(28, 70, 86 * (1 - clamp(p.dashCd / p.dashCooldown, 0, 1)), 5);
    this.drawMarkers(c); const prompt = this.contextPrompt(); if (prompt) { c.textAlign = 'center'; c.fillStyle = 'rgba(11,4,22,.82)'; c.fillRect(340, 487, 280, 28); c.strokeStyle = COLORS.cyan; c.lineWidth = 1.5; c.strokeRect(340.5, 487.5, 279, 27); c.fillStyle = COLORS.bone; c.font = 'bold 13px monospace'; c.fillText(prompt, 480, 495); }
    if (this.mission) { c.textAlign = 'center'; c.font = 'bold 13px monospace'; c.fillStyle = COLORS.hotPink; c.fillText(`MISSION ${this.missionIndex + 1}/${MISSION_COUNT} — ${this.mission.name}`, 480, 18); c.font = '11px monospace'; c.fillStyle = this.goalDone ? COLORS.cyan : COLORS.orange; c.fillText(this.objectiveText(), 480, 36); if (this.missionTime < 4.5) { c.fillStyle = COLORS.bone; c.fillText(this.mission.sub, 480, 52); } }
    const tut = this.tutorialText(); if (tut) { c.textAlign = 'center'; c.font = 'bold 14px monospace'; c.fillStyle = 'rgba(11,4,22,.68)'; c.fillRect(340, 92, 280, 25); c.fillStyle = COLORS.cyan; c.fillText(tut, 480, 98); }
    if (this.hurtFlash > 0) { const a = Math.min(.5, this.hurtFlash * .5); const vg = c.createRadialGradient(480, 270, 120, 480, 270, 520); vg.addColorStop(0, 'rgba(160,0,20,0)'); vg.addColorStop(1, `rgba(180,0,25,${a})`); c.fillStyle = vg; c.fillRect(0, 0, 960, 540); }
    c.restore(); this.drawReticle(c);
  },
  contextPrompt() { if (this.goalDone && this.level.exit.active && dist(this.player, this.level.exit) < 52) return '[E] ESCAPE'; if (!this.goalDone && this.mission && this.mission.goal.type === 'retrieve' && this.level.objective && !this.level.objective.taken && dist(this.player, this.level.objective) < 55) return `[E] TAKE ${this.level.objective.label}`; for (const e of this.enemies) if (!e.dead && e.stun > 0 && dist(this.player, e) < 42) return '[SPACE] FINISH'; for (const p of this.level.pickups) if (!p.taken && dist(this.player, p) < 48) return `[E] TAKE ${p.weapon.name.toUpperCase()}`; const d = this.level.nearestDoor(this.player, 58); if (d && !d.open) return '[E] OPEN  /  [SPACE] BREACH'; return ''; },
  objectiveText() { if (this.goalDone) return 'REACH THE EXIT'; if (!this.mission) return ''; const g = this.mission.goal; if (g.type === 'eliminate') return 'ELIMINATE ALL HOSTILES'; if (g.type === 'target') return 'KILL THE MARKED MAN'; if (g.type === 'boss') return 'KILL THE PORTER'; if (g.type === 'retrieve') return 'TAKE ' + (this.level.objective ? this.level.objective.label : 'THE OBJECTIVE'); return ''; },
  tutorialText() { if (this.missionIndex !== 0) return ''; if (this.missionTime < 3.8) return 'WASD  MOVE'; if (this.missionTime < 7.5) return 'MOUSE  AIM'; if (this.missionTime < 11) return 'CLICK  ATTACK'; if (this.missionTime < 14.5) return 'E  PICK UP / OPEN'; if (this.missionTime < 18) return 'SHIFT  DASH'; return ''; },
  drawReticle(c) { const m = this.input.mouse; c.save(); c.translate(m.x, m.y); c.strokeStyle = this.settings.highContrastCursor ? '#ffffff' : COLORS.cyan; c.lineWidth = 1.5; const r = 8 + (this.player?.attackCd || 0) * 7; c.beginPath(); c.moveTo(-r - 5, 0); c.lineTo(-r, 0); c.moveTo(r, 0); c.lineTo(r + 5, 0); c.moveTo(0, -r - 5); c.lineTo(0, -r); c.moveTo(0, r); c.lineTo(0, r + 5); c.stroke(); c.restore(); },
  drawPost(c) { if (!this.settings.post) return; c.save(); const g = c.createRadialGradient(480, 270, 180, 480, 270, 570); g.addColorStop(0, 'rgba(0,0,0,0)'); g.addColorStop(1, 'rgba(0,0,0,.55)'); c.fillStyle = g; c.fillRect(0, 0, 960, 540); c.globalAlpha = .035; c.fillStyle = '#fff'; for (let i = 0; i < 55; i++) c.fillRect((i * 137 + performance.now() * .02) % 960, (i * 83) % 540, 1, 1); c.restore(); },
  drawMenu(c) { if (!(this.renderer && this.renderer.available)) { c.fillStyle = COLORS.void; c.fillRect(0, 0, 960, 540); } c.save(); c.translate(275, 178); c.rotate(-.08); c.shadowColor = COLORS.hotPink; c.shadowBlur = 20; c.fillStyle = COLORS.bone; c.beginPath(); c.moveTo(-60, -78); c.lineTo(20, -88); c.lineTo(74, -40); c.lineTo(65, 38); c.lineTo(3, 78); c.lineTo(-70, 39); c.lineTo(-85, -28); c.closePath(); c.fill(); c.shadowBlur = 0; c.fillStyle = COLORS.ink; c.fillRect(-20, -38, 32, 10); c.fillRect(23, 0, 34, 8); c.fillRect(-52, 8, 28, 7); c.fillStyle = COLORS.hotPink; c.fillRect(50, -34, 11, 47); c.restore(); c.textAlign = 'left'; c.fillStyle = COLORS.bone; c.font = 'bold 46px monospace'; c.fillText('VEIL//DRIVE', 385, 150); c.font = '13px monospace'; c.fillStyle = COLORS.cyan; c.fillText('MOTEL STATIC — A NEON CRIME ROGUELITE', 389, 175); const items = ['START RUN', `MASK / ${this.save.selectedMask}`, 'SETTINGS', 'CREDITS', 'RELOAD PAGE']; for (let i = 0; i < items.length; i++) { const y = 270 + i * 40; c.fillStyle = i === this.menuIndex ? COLORS.hotPink : '#6f5f7a'; c.font = i === this.menuIndex ? 'bold 18px monospace' : '16px monospace'; c.fillText(`${i === this.menuIndex ? '› ' : ''}${items[i]}`, 390, y); } c.font = '10px monospace'; c.fillStyle = '#786f79'; c.fillText('← → CHANGE UNLOCKED MASK WHEN SELECTED', 390, 474); c.font = '11px monospace'; c.fillStyle = COLORS.orange; c.fillText(`BEST ${this.save.bestRank}  ${String(this.save.highScore).padStart(6, '0')}  //  RUNS ${this.save.runs}`, 390, 493); c.fillStyle = '#8f7f9a'; c.fillText('ENTER / CLICK SELECT   •   ↑↓ NAVIGATE', 390, 512); },
  drawSettings(c) { c.fillStyle = 'rgba(11,4,22,.86)'; c.fillRect(0, 0, 960, 540); c.fillStyle = COLORS.bone; c.font = 'bold 30px monospace'; c.fillText('SETTINGS / ACCESSIBILITY', 90, 70); const entries = [['MASTER', 'master'], ['MUSIC', 'music'], ['SFX', 'sfx'], ['SCREEN SHAKE', 'shake'], ['BLOOD FX', 'blood'], ['GRAPHICS QUALITY', 'quality'], ['POST PROCESS', 'post'], ['PIXEL WORLD', 'pixel'], ['FLASHING', 'flashes'], ['HIGH-CONTRAST CURSOR', 'highContrastCursor']]; for (let i = 0; i < entries.length; i++) { const [name, k] = entries[i], y = 120 + i * 36; c.fillStyle = i === this.settingsIndex ? COLORS.hotPink : '#8f7f9a'; c.font = i === this.settingsIndex ? 'bold 15px monospace' : '14px monospace'; c.fillText(name, 130, y); const v = this.settings[k]; c.textAlign = 'right'; c.fillStyle = i === this.settingsIndex ? COLORS.cyan : COLORS.bone; c.fillText(typeof v === 'boolean' ? (v ? 'ON' : 'OFF') : `${Math.round(v * 100)}%`, 780, y); c.textAlign = 'left'; } c.fillStyle = '#8f7f9a'; c.font = '11px monospace'; c.fillText('↑↓ SELECT   ←→ ADJUST   ESC SAVE/BACK', 130, 488); },
  drawCredits(c) { c.fillStyle = 'rgba(11,4,22,.86)'; c.fillRect(0, 0, 960, 540); c.textAlign = 'center'; c.fillStyle = COLORS.bone; c.font = 'bold 30px monospace'; c.fillText('VEIL//DRIVE', 480, 90); c.font = '13px monospace'; c.fillStyle = COLORS.cyan; c.fillText('Original browser prototype', 480, 130); c.fillStyle = '#9e8fa8'; c.fillText('Code, procedural art, synthesis and systems generated for this project.', 480, 174); c.fillText('No third-party art, music, sound, or game assets are included.', 480, 198); c.fillStyle = COLORS.hotPink; c.fillText('Protagonist: MOTH-0  •  Boss: THE PORTER', 480, 242); c.fillStyle = '#8f7f9a'; c.fillText('ESC / ENTER BACK', 480, 450); c.textAlign = 'left'; },
  drawUpgrade(c) { c.fillStyle = 'rgba(11,4,22,.82)'; c.fillRect(0, 0, 960, 540); c.textAlign = 'center'; c.fillStyle = COLORS.bone; c.font = 'bold 24px monospace'; c.fillText('CHOOSE A BAD HABIT', 480, 115); for (let i = 0; i < 3; i++) { const x = 135 + i * 235, u = this.upgradeChoices[i]; c.fillStyle = 'rgba(26,10,51,.92)'; c.fillRect(x, 165, 205, 190); c.strokeStyle = i === 1 ? COLORS.hotPink : COLORS.violet; c.lineWidth = 2; c.strokeRect(x + 1, 166, 203, 188); c.fillStyle = COLORS.hotPink; c.font = 'bold 13px monospace'; c.fillText(`[${i + 1}]`, x + 102, 190); c.fillStyle = COLORS.bone; c.font = 'bold 15px monospace'; c.fillText(u.name, x + 102, 225); c.fillStyle = COLORS.cyan; c.font = '12px monospace'; this.wrapText(c, u.desc, x + 102, 260, 170, 18); } c.fillStyle = '#8f7f9a'; c.font = '11px monospace'; c.fillText('1 / 2 / 3 OR CLICK', 480, 395); c.textAlign = 'left'; },
  wrapText(c, text, x, y, max, line) { const words = text.split(' '); let row = ''; for (const w of words) { const test = row + w + ' '; if (c.measureText(test).width > max) { c.fillText(row, x, y); y += line; row = w + ' '; } else row = test; } c.fillText(row, x, y); },
  drawPause(c) { c.fillStyle = 'rgba(11,4,22,.82)'; c.fillRect(0, 0, 960, 540); c.textAlign = 'center'; c.fillStyle = COLORS.bone; c.font = 'bold 28px monospace'; c.fillText('PAUSED', 480, 168); const items = ['RESUME', 'RESTART MISSION', 'QUIT TO MENU']; for (let i = 0; i < 3; i++) { const y = 244 + i * 46; c.fillStyle = i === this.pauseIndex ? COLORS.hotPink : '#8f7f9a'; c.font = i === this.pauseIndex ? 'bold 18px monospace' : '15px monospace'; c.fillText(`${i === this.pauseIndex ? '› ' : ''}${items[i]}`, 480, y); } c.fillStyle = '#8f7f9a'; c.font = '11px monospace'; c.fillText('↑↓ SELECT   •   ENTER CONFIRM   •   ESC RESUME', 480, 438); c.textAlign = 'left'; },
  drawIntro(c) { if (!this.mission || (this.introT || 0) > 3.6) return; const t = this.introT || 0; const a = t < 2.6 ? 1 : Math.max(0, 1 - (t - 2.6)); c.save(); c.globalAlpha = a; c.fillStyle = 'rgba(11,4,22,.74)'; c.fillRect(0, 196, VIRTUAL_W, 150); c.strokeStyle = COLORS.hotPink; c.lineWidth = 2; c.strokeRect(0.5, 196.5, VIRTUAL_W - 1, 149); c.textAlign = 'center'; c.fillStyle = COLORS.cyan; c.font = 'bold 12px monospace'; c.fillText(`MISSION ${this.missionIndex + 1} / ${MISSION_COUNT}`, 480, 222); c.fillStyle = COLORS.bone; c.font = 'bold 30px monospace'; c.fillText(this.mission.name, 480, 258); c.fillStyle = '#c9b7d8'; c.font = '12px monospace'; this.wrapText(c, this.mission.sub, 480, 284, 540, 16); c.fillStyle = COLORS.orange; c.font = 'bold 13px monospace'; c.fillText(this.objectiveText(), 480, 322); const alive = this.enemies.filter(e => !e.dead).length + (this.boss && !this.boss.dead ? 1 : 0); c.fillStyle = COLORS.magenta; c.font = '11px monospace'; c.fillText(`HOSTILES ${alive}`, 480, 340); c.textAlign = 'left'; c.restore(); },
  drawInterlude(c) { c.fillStyle = 'rgba(11,4,22,.6)'; c.fillRect(0, 0, 960, 540); c.textAlign = 'center'; c.fillStyle = COLORS.hotPink; c.font = 'bold 38px monospace'; c.fillText('MISSION COMPLETE', 480, 236); c.fillStyle = COLORS.bone; c.font = 'bold 16px monospace'; c.fillText(this.mission ? this.mission.name : '', 480, 272); c.fillStyle = COLORS.cyan; c.font = '13px monospace'; c.fillText(`${this.missionTime.toFixed(1)}s    HOSTILES DOWN ${this.killCount}    SCORE ${String(this.score).padStart(6, '0')}`, 480, 300); c.fillStyle = COLORS.orange; c.font = '11px monospace'; c.fillText(this.missionIndex >= MISSION_COUNT - 1 ? 'FINAL RESULTS…' : `NEXT: ${MISSIONS[this.missionIndex + 1].name}`, 480, 330); const t = clamp((this.interludeT || 0) / 1.6, 0, 1); c.fillStyle = COLORS.ink; c.fillRect(340, 352, 280, 5); c.fillStyle = COLORS.hotPink; c.fillRect(340, 352, 280 * t, 5); c.textAlign = 'left'; },
  drawDeath(c) { c.fillStyle = 'rgba(255,10,60,.12)'; c.fillRect(0, 0, 960, 540); c.textAlign = 'center'; c.fillStyle = COLORS.blood; c.font = 'bold 30px monospace'; c.fillText('SIGNAL LOST', 480, 250); c.font = '12px monospace'; c.fillStyle = COLORS.hotPink; c.fillText('REWINDING…', 480, 285); c.textAlign = 'left'; },
  drawResults(c) { if (!c) return; const r = this.results; c.fillStyle = 'rgba(11,4,22,.86)'; c.fillRect(0, 0, 960, 540); c.fillStyle = COLORS.bone; c.font = 'bold 26px monospace'; c.fillText('CAMPAIGN // CLOSED FILE', 100, 72); c.fillStyle = COLORS.hotPink; c.font = 'bold 86px monospace'; c.fillText(r.rank, 720, 92); c.font = '13px monospace'; const rows = [['RUN VALUE', r.value], ['COMBAT SCORE', r.score], ['MISSIONS', `${r.missions}/${MISSION_COUNT}`], ['CLEAR TIME', `${r.time.toFixed(1)}s`], ['ACCURACY', `${r.accuracy}%`], ['MAX CHAIN', `x${r.combo}`], ['DEATHS', r.deaths], ['WEAPON VARIETY', r.variety], ['SILENT KILLS', r.stealth]]; for (let i = 0; i < rows.length; i++) { const y = 150 + i * 34; c.fillStyle = '#8f7f9a'; c.fillText(rows[i][0], 130, y); c.fillStyle = COLORS.bone; c.fillText(String(rows[i][1]), 430, y); } if (r.unlocks?.length) { c.fillStyle = COLORS.cyan; c.fillText(`UNLOCKED MASK: ${r.unlocks.join(' / ')}`, 130, 440); } c.fillStyle = '#8f7f9a'; c.fillText('ENTER MENU   •   R RUN AGAIN', 130, 472); },
  drawMarkers(c) {
    const cx = VIRTUAL_W / 2, cy = VIRTUAL_H / 2, mx = 26, my = 22;
    const w2s = (x, y) => ({ x: x - this.cam.x + this.shakeX, y: y - this.cam.y + this.shakeY });
    const chevron = (sx, sy, color) => {
      const dx = sx - cx, dy = sy - cy, ang = Math.atan2(dy, dx);
      const hx = clamp(cx + Math.cos(ang) * (cx - mx), mx, VIRTUAL_W - mx);
      const hy = clamp(cy + Math.sin(ang) * (cy - my), my, VIRTUAL_H - my);
      c.save(); c.translate(hx, hy); c.rotate(ang); c.fillStyle = color; c.globalAlpha = .92;
      c.beginPath(); c.moveTo(13, 0); c.lineTo(-7, -9); c.lineTo(-7, 9); c.closePath(); c.fill(); c.restore(); c.globalAlpha = 1;
    };
    let target = null;
    const ob = this.level.objective;
    if (!this.goalDone && this.mission && this.mission.goal.type === 'retrieve' && ob && !ob.taken) target = ob;
    else if (!this.goalDone && this.mission && this.mission.goal.type === 'target' && this.target && !this.target.dead) target = this.target;
    else if (this.goalDone && this.level.exit.active) target = this.level.exit;
    if (target) { const s = w2s(target.x, target.y); if (s.x < mx || s.x > VIRTUAL_W - mx || s.y < my || s.y > VIRTUAL_H - my) chevron(s.x, s.y, COLORS.cyan); }
    for (const e of this.enemies) { if (e.dead || e.state !== 'COMBAT') continue; const s = w2s(e.x, e.y); if (s.x < mx || s.x > VIRTUAL_W - mx || s.y < my || s.y > VIRTUAL_H - my) chevron(s.x, s.y, COLORS.blood); }
    const alive = this.enemies.filter(e => !e.dead).length + (this.boss && !this.boss.dead ? 1 : 0);
    c.save(); c.textAlign = 'right'; c.font = 'bold 12px monospace'; c.fillStyle = this.boss && !this.boss.dead ? COLORS.magenta : (alive ? COLORS.orange : COLORS.cyan);
    c.fillText(this.boss && !this.boss.dead ? 'BOSS' : `HOSTILES ${alive}`, VIRTUAL_W - 22, 44); c.restore();
  },
  drawDebug(c) { c.fillStyle = 'rgba(0,0,0,.7)'; c.fillRect(8, 90, 170, 90); c.fillStyle = '#7be0d8'; c.font = '10px monospace'; c.fillText(`FPS ${this.fps}`, 16, 101); c.fillText(`XY ${this.player.x | 0},${this.player.y | 0}`, 16, 116); c.fillText(`AI ${this.enemies.filter(e => !e.dead).length}`, 16, 131); c.fillText(`STATE ${this.state}`, 16, 146); c.fillText(`F2 GOD ${this.invincible ? 'ON' : 'OFF'}  F3 SPAWN F4 CLEAR`, 16, 161); c.save(); c.translate(-this.cam.x, -this.cam.y); for (const e of this.enemies) { if (e.dead) continue; c.strokeStyle = 'rgba(80,220,210,.22)'; c.beginPath(); c.moveTo(e.x, e.y); c.arc(e.x, e.y, e.vision, e.a - e.fov / 2, e.a + e.fov / 2); c.closePath(); c.stroke(); } c.restore(); }
};
